### ISSUE TITLE
Feature Request: expose class decorator without define call

### ISSUE THREAD

**Issue by gluck** [preactjs/preact-custom-element#17]
Hi,

I need to expose a preact component as an _unregistered_ custom element (so that the end user will call `customElements.define` with the tag name of its choosing).

WDYT about also exporting the class decoration without define call ?

We could keep the current default export for backward compatibility, yet (also) export named functions `registerCustomElement` and `createCustomElement` (or similar) ?

I can work out the PR if you think that's a worthy addition to this library !

Thanks.

**Comment by developit** [comment]
This will work once #23 is merged:

```js
@register
class Greeting {
    static tagName = 'gree-ting';
    static observedAttributes = ['name'];
    render({ name }) {
        return <span>Hello, {name}!</span>
    }
}

document.body.innerHTML = '<gree-ting name="gluck"></gree-ting>';
```
