### ISSUE TITLE
Help wanted: How to build & export a custom element

### ISSUE THREAD

**Issue by secretlifeof** [preactjs/preact-custom-element#28]
Hey and thank you very much for this!

I am trying to build a npm package that exports a custom-element, but I am struggling how to make this work. Trying different bundlers (Webpack, Rollup, Microbundle, Snowpack) without success. Preact-cli widget is not up to date.

Here is what I have so far:
```
import { h } from 'preact'
import { setPragma, styled } from 'goober'
import htm from 'htm'
import register from 'preact-custom-element'
const html = htm.bind(h)

setPragma(h)

const RedText = styled('span')`
  color: red;
`

const App = () =>
  html`
    <${RedText}><div>There you are</div><//>
  `

register(
  html`
    <${App} />
  `,
  'hi-hi-app',
  []
)
```

I use microbundle@next ("microbundle --alias react=preact/compat,react-dom=preact/compat") to build the scripts

When trying to import this package in Nextjs I get this error:

> InvalidCharacterError: Failed to execute 'createElement' on 'Document': The tag name provided ('[object Object],>') is not a valid name.
> 
> import{hydrate as t,render as e,cloneElement as n,h as o}from"preact";import{setPragma as r,styled as i}from"goober";import u from"htm";function c(t,e){return e||(e=t.slice(0)),t.raw=e,t}function a(){this._vdom=function t(e,n){if(3===e.nodeType)return e.data;if(1!==e.nodeType)return null;var r=[],i={},u=0,c=e.attributes,a=e.childNodes;for(u=c.length;u--;)i[c[u].name]=c[u].value;for(u=a.length;u--;)r[u]=t(a[u]);return o(n||e.nodeName.toLowerCase(),i,r)}(this,this._vdomComponent),(this.hasAttribute("hydrate")?t:e)(this._vdom,this)}function d(t,o,r){if(this._vdom){var i={};i[t]=r,this._vdom=n(this._vdom,i),e(this._vdom,this)}}function s(){e(this._vdom=null,this)}function l(){var t=c(["\n    <div>TEST</div>>\n  "]);return l=function(){return t},t}function m(){var t=c(["\n    <","><div>THERE Here</div><//>\n  "]);return m=function(){return t},t}function p(){var t=c(["\n  display: flex;\n  flex: 1;\n  color: red;\n  width: 300px;\n  height: 300px;\n  background: yellow;\n"]);return p=function(){return t},t}var f=u.bind(o);r(o);var h=i("span")(p());console.log(()=>f(m(),h)),function(t,e,n){function o(){var e=Reflect.construct(HTMLElement,[],o);return e._vdomComponent=t,e}(o.prototype=Object.create(HTMLElement.prototype)).constructor=o,o.prototype.connectedCallback=a,o.prototype.attributeChangedCallback=d,o.prototype.detachedCallback=s,o.observedAttributes=[]||t.observedAttributes||Object.keys(t.propTypes||{}),customElements.define("pimello-cms",o)}(f(l()));

If anybody can point me towards a boilerplate that would be great :)

**Comment by georges-gomes** [comment]
Hi!
Checkout webcomponents.dev
There is a template for Preact component wrapped in custom-element.
There is also an automatic npm package deployment.
But I will be happy to help in our chat (spectrum.chat/webcomponents-dev) if you want to bundle it on your own.
Cheers

**Comment by secretlifeof** [comment]
Thanks a lot @georges-gomes for your fast answer. webcomponents.dev is a good source :)

My problem. I wrote
```
register(
  html`
    <${App} />
  `,
  'hi-hi-app',
  []
)
```

and it should be
```
register(
  App,
  'hi-hi-app',
  []
)
```

**Comment by qidian99** [comment]
Hi,

I have a similar problem -- when I exported the template using `preact build --template`, I tried to import it in html local server for testing, but it threw an error "module is not undefined".

**Comment by peterwiebe** [comment]
hey @georges-gomes I was also wanting to figure out how to build the web component locally, do you have a recommended way of doing this?

**Comment by peterwiebe** [comment]
for reference, I tried building with the latest version of Vite but it includes `process.env` in the build which is not available in the browser
