### ISSUE TITLE
Can we make this work for SSR?

### ISSUE THREAD

**Issue by secretlifeof** [preactjs/preact-custom-element#29]
Here is a sandbox trying to combine **Preact** inside a custom element with **Nextjs**. But it errors 
> Warning: Did not expect server HTML to contain a \<div\> in \<custom-element\>

https://codesandbox.io/s/github/secretlifeof/nextjs-dynamic-import-issue/tree/custom-element-ssr/

Is there a possibility to make this work for SSR? It tried adding "window !== undefined" but that always caused some other errors. To be honest I am too much of a newbie to really understand how this script works. If anybody can give me some hints I would love to try to contribute though.

**Comment by secretlifeof** [comment]
This was not a problem with preact-custom-element. It was probably server side rendering an unknown tagname like \<custom-element\>

How this was solved inside Nextjs
```
const CustomElementFrame = () => {
  const refContainer = useRef(null)

  useEffect(() => {
    var node = document.createElement('custom-element')
    refContainer.current.appendChild(node)
  })

  return (
    <div ref={refContainer}>
    </div>
  )
}
```

Should we add this to the top of the register function or just leave it like it is?
```
if (typeof window === 'undefined') {
  return null
}
```

**Comment by bspaulding** [comment]
Perhaps logging a warning in this case and directing people here would be prudent/helpful?

**Comment by secretlifeof** [comment]
Thank you for your answer @bspaulding! I will close this for now. People having trouble with SSR rendering will hopefully search for and land on this page.
