### ISSUE TITLE
Children of custom element gets rendered twice

### ISSUE THREAD

**Issue by donpark** [preactjs/preact-custom-element#32]
This may be related to #18 but when custom element renders its children property like this:

```
const Greeting = ({ children, name = "World" }) => (
  <h1 id="hello">
    <p>Hello {name}!</p>
    {children}
  </h1>
);
```

They are rendered twice in two different styles (shadow and document?) like this:

<img width="534" alt="screenshot_1031" src="https://user-images.githubusercontent.com/127594/82124849-b05ba880-9756-11ea-9673-f51ece37ff95.png">

See: https://codesandbox.io/s/preact-custom-element-rendering-content-issue-g7ko9

I also noticed in some test cases where the custom element, not just children, gets rendered twice when some elements are added. When traced in such cases, `children` property included the root element (direct children of `shadowRoot`) instead of the children from HTML.

Looking at `preact-custom-element` source code, I'm having difficulty finding where `children` parameter comes from. In my 'bare-metal' custom element  implementation, I capture `children` via a `MutationObserver` like this:

```
    connectedCallback() {
        const shadowRoot = this.shadowRoot;
        var observer = new MutationObserver(function (mutations) {
            mutations.forEach((mutation) => {
                for (const child of mutation.addedNodes) {
                    shadowRoot.querySelector('.info').appendChild(child)
                }
            })
        })
        observer.observe(this, { childList: true })
    }
```

**Comment by donpark** [comment]
nvm. It looks like adding an unnamed `slot` fixes the problem. There were some odd behaviors while I was tinkering with the fix but seemingly unrelated changes made them unreproducible.
Closing.

**Comment by mknet** [comment]
@donpark Could publish a short example showing your solution with the unnamed slot?
I'd appreciate it! Thx!

**Comment by donpark** [comment]
With HTML emitted using PHP like this:
```php
    <div class="<?php echo $blockSpec['outerClassName']; ?>">
        <talk-section id="talk-block-<?php echo $attributes['blockId']; ?>" display="gutenberg">
            <div class="talk-content">
                <?php echo $inner_blocks; ?>
            </div>
            <script type="application/json" class="talk-data">
                <?php echo $data; ?>
            </script>
        </talk-section>
    </div>
```
And custom element `talk-section`'s renderer looks like this:
```javascript
        return [
            <link rel="stylesheet" href="/wp-content/plugins/talk/elements/index.css" media="all"></link>,
            <div ref={this.sectionRef} className="talk-section" style={sectionStyle}>
                <slot />
                <TalkAudio
                    autoLevel={autoLevel}
                    autoPlay={autoPlay}
                    recording={recording}
                    audioRef={this.audioRef}
                ></TalkAudio>
                {chyronComponent}
            </div>,
        ];
```
DOM will look like this:
<img width="793" alt="screenshot_1059" src="https://user-images.githubusercontent.com/127594/83809800-ef9d5b00-a66b-11ea-9d8f-7d7ed27652cc.png">

Child elements of the custom element get mapped as children of the slot element, allowing the custom element to position them anywhere within its hierarchy.

**Comment by mbohgard** [comment]
@donpark Hi. I'm having the same issue. Can't get it to work somehow with the unnamed slot. Can you alter your codesandbox sample to actually solve the issue? Thank you!

**Comment by donpark** [comment]
@mbohgard here is the fixed sample
https://codesandbox.io/s/preact-custom-element-rendering-content-issue-forked-38xpc?file=/src/index.js

In short,

1. Add an unnamed `<slot />`
2. Remove `{children}`

**Comment by marvinhagemeister** [comment]
@mbohgard @donpark There is no need to use an unnamed `<slot>`-node instead of just passing `{children}`. Instead, to resolve this issue one only needs to update to the latest version of `preact-custom-element`. At the time of the writing this is `4.1.0`. See this [codesandbox](https://codesandbox.io/s/preact-custom-element-rendering-content-issue-forked-3rmtk?file=/src/index.js) :+1:

**Comment by mbohgard** [comment]
@marvinhagemeister Thanks! I had issues with that tho as described [here](https://github.com/preactjs/preact-custom-element/issues/41).

**Comment by mufaddalmw** [comment]
> @mbohgard @donpark There is no need to use an unnamed `<slot>`-node instead of just passing `{children}`. Instead, to resolve this issue one only needs to update to the latest version of `preact-custom-element`. At the time of the writing this is `4.1.0`. See this [codesandbox](https://codesandbox.io/s/preact-custom-element-rendering-content-issue-forked-3rmtk?file=/src/index.js) 👍

How to achieve same behavior when shadow: false is applied.
