### ISSUE TITLE
detachedcallback should be disconnectedcallback

### ISSUE THREAD

**Issue by filipbech** [preactjs/preact-custom-element#37]
I might be totally off here, but if I understand the source correctly you are listening for the old v0 callback that the browser nolonger fires - so cleanup wont happen.  

https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements#Using_the_lifecycle_callbacks

This might be something specific to preact (where Im no expert), in which case you can just close this issue. 

Would you like me to do a PR for this change?

**Comment by marvinhagemeister** [comment]
Good catch! That is indeed a bug and it should be changer to `disconnectedCallback`. Would love a PR for this 👍

**Comment by marvinhagemeister** [comment]
Fixed by #38
