### ISSUE TITLE
I can't use hook

### ISSUE THREAD

**Issue by X7md** [preactjs/preact-custom-element#60]
My Code
![image](https://user-images.githubusercontent.com/54203033/117326041-f47d1700-ae99-11eb-8755-a35706573d99.png)

Console Error 
![image](https://user-images.githubusercontent.com/54203033/117326114-0494f680-ae9a-11eb-82c3-5b59d0a2efd7.png)

----
But work fine without hook

Code:
![image](https://user-images.githubusercontent.com/54203033/117326585-78370380-ae9a-11eb-9795-f1d615a54bb4.png)

browser:
![image](https://user-images.githubusercontent.com/54203033/117326638-871db600-ae9a-11eb-8d95-33d0900e427c.png)

**Comment by nicola-bovolato** [comment]
I'm having the same issue, any updates on this?

**Comment by X7md** [comment]
> I'm having the same issue, any updates on this?

unfortunately, no...

But try use it through JavaScript Bundler like 
https://vitejs.dev for example

**Comment by X7md** [comment]
Close because the is no answer، or workaround
