### ISSUE TITLE
Generating preact-ce.module.js

### ISSUE THREAD

**Issue by emindeniz99** [preactjs/preact-custom-element#77]
Hello,
I cannot find how to generate preact-ce.module.js from source code.

https://www.jsdelivr.com/package/npm/preact-custom-element?path=dist

<img width="963" alt="image" src="https://user-images.githubusercontent.com/44745432/196025522-602c6494-6b1b-4825-87af-8417cf699f24.png">

when I build on my local environment, I could not find
<img width="359" alt="image" src="https://user-images.githubusercontent.com/44745432/196025633-07bad3de-4795-48d1-b141-46b10da614e6.png">

**Comment by rschristian** [comment]
In all likelihood it's a left over artifact from a previous build; Microbundle doesn't clear out the `dist/` directory on rebuild and the fact that there's no `preact-ce.modern.js` to me is a bit of a hint that Microbundle might've been ran, upgraded to a new version, then re-ran, leaving left over files to be published.

None are referenced by the `package.json`, so they're not meant for use. A publish mistake is most likely.
