### ISSUE TITLE
how to publish and then use my web component in other websites?

### ISSUE THREAD

**Issue by da1z** [preactjs/preact-custom-element#86]
is there any guide how to properly publish web component? to npm maybe? and then use it through embedding script ?

**Comment by rschristian** [comment]
No guide exists as far as I'm aware as it's no different from any other library really.

Is there anything in particular you're looking for/confused on?

**Comment by da1z** [comment]
> No guide exists as far as I'm aware as it's no different from any other library really.
> 
> Is there anything in particular you're looking for/confused on?

yes. i want to make a component that can be used any any web page by jest embedding script tag . The question is how to setup my project to make script output ?

**Comment by rschristian** [comment]
Do you want a widget, or a widget and a component library?

Here's an example of a widget, it's nothing fancy: https://github.com/rschristian/demo__preact-custom-element-widget

**Comment by da1z** [comment]
Just widget. No component library

**Comment by rschristian** [comment]
Then that should do it.
