### ISSUE TITLE
host css styles applied to component?

### ISSUE THREAD

**Issue by da1z** [preactjs/preact-custom-element#87]
Am I doing something wrong? as i understand global styles should no apply to shadow root elements but for some reason it does. My code:

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="color-scheme" content="light dark" />
    <title>Vite + Preact</title>
    <style>
      body {
        color: green;
      }
    </style>
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="/src/index.tsx"></script>
  </body>
</html>
```

index.tsx
```
import { render } from 'preact';

import register from 'preact-custom-element';
// import './style.css';

const Greeting = ({ name = 'World' }) => <p>Hello, {name}!</p>;
register(Greeting, 'x-greeting', ['name'], { shadow: true, mode: 'closed' });

export function App() {
  return (
    <div>
      <x-greeting name="Billy Jo"></x-greeting>
    </div>
  );
}

render(<App />, document.getElementById('app'));

```

and result is text is green

<img width="222" alt="Screenshot 2024-05-06 at 5 42 33 PM" src="https://github.com/preactjs/preact-custom-element/assets/4012422/f411d9dd-1502-41d6-90e8-bbf363992741">
<img width="560" alt="Screenshot 2024-05-06 at 5 42 39 PM" src="https://github.com/preactjs/preact-custom-element/assets/4012422/c4b9a9d1-9fc2-4ccb-acab-a668c3eb4337">

**Comment by marvinhagemeister** [comment]
This is how shadow DOM works. Quoting [the specification](https://www.w3.org/TR/css-scoping/#shadow-cascading) on how cascading styles works:

> The [top-level elements](https://www.w3.org/TR/css-scoping/#top-level-element) of a [shadow tree](https://www.w3.org/TR/css-scoping/#shadow-tree) inherit from their [host element](https://www.w3.org/TR/css-scoping/#host-element0).

See also this explanation on StackOverflow: https://stackoverflow.com/questions/49709676/light-dom-style-leaking-into-shadow-dom
